"""empty message

Revision ID: 0b4c5d536537
Revises: 1b773a10c4bb
Create Date: 2020-09-17 22:30:10.592742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4c5d536537'
down_revision = '1b773a10c4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jutesurveyinputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('plotarea', sa.Integer(), nullable=False),
    sa.Column('soiltype', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jutesurveyinputs')
    # ### end Alembic commands ###
