"""empty message

Revision ID: d1547babca31
Revises: 0b4c5d536537
Create Date: 2020-09-23 16:05:08.196530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1547babca31'
down_revision = '0b4c5d536537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jutesurveyinputs', sa.Column('amountofseed', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('availabilityofwater', sa.Boolean(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('dateofharvest', sa.DateTime(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('dateofsowing', sa.DateTime(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('daysleftforharvest', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('daysrequiredforcompleteretting', sa.String(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('humidity', sa.String(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('methodofretting', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('methodofsowing', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('methodofweeding', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('nitrogenamount', sa.Numeric(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('organiccarbonamount', sa.Numeric(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('phosphorousamount', sa.Numeric(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('pottasiumamount', sa.Numeric(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('qualityofwashingwater', sa.Boolean(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('rainfall', sa.Numeric(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('soilhealthcard', sa.Boolean(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('sourceofwater', sa.Integer(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('temperature', sa.String(), nullable=True))
    op.add_column('jutesurveyinputs', sa.Column('varietyused', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jutesurveyinputs', 'varietyused')
    op.drop_column('jutesurveyinputs', 'temperature')
    op.drop_column('jutesurveyinputs', 'sourceofwater')
    op.drop_column('jutesurveyinputs', 'soilhealthcard')
    op.drop_column('jutesurveyinputs', 'rainfall')
    op.drop_column('jutesurveyinputs', 'qualityofwashingwater')
    op.drop_column('jutesurveyinputs', 'pottasiumamount')
    op.drop_column('jutesurveyinputs', 'phosphorousamount')
    op.drop_column('jutesurveyinputs', 'organiccarbonamount')
    op.drop_column('jutesurveyinputs', 'nitrogenamount')
    op.drop_column('jutesurveyinputs', 'methodofweeding')
    op.drop_column('jutesurveyinputs', 'methodofsowing')
    op.drop_column('jutesurveyinputs', 'methodofretting')
    op.drop_column('jutesurveyinputs', 'humidity')
    op.drop_column('jutesurveyinputs', 'daysrequiredforcompleteretting')
    op.drop_column('jutesurveyinputs', 'daysleftforharvest')
    op.drop_column('jutesurveyinputs', 'dateofsowing')
    op.drop_column('jutesurveyinputs', 'dateofharvest')
    op.drop_column('jutesurveyinputs', 'availabilityofwater')
    op.drop_column('jutesurveyinputs', 'amountofseed')
    # ### end Alembic commands ###
